locust result uplooad ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,7 +27,6 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install boto3 Flask pytest awscli
-
       - name: "Configurar credenciales AWS"
         uses: aws-actions/configure-aws-credentials@v2
         with:
@@ -70,7 +69,11 @@ jobs:
         run: |
           pip install locust
           echo "Prueba de carga en: $LB_URL"
-          locust -f src/locustfile.py --headless -u 100 -r 10 -t 1m --host $LB_URL
+          locust -f src/locustfile.py --headless -u 100 -r 10 -t 1m --host $LB_URL --html locust_result.html
+          if [ ! -f "locust_result.html" ]; then
+            echo "Error: El archivo locust_result.html no se generó correctamente."
+            exit 1
+          fi
 
       - name: "Subir resultados de rendimiento a S3"
         env:
@@ -79,5 +82,6 @@ jobs:
           AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
         run: |
           aws s3 ls "s3://performance-reports-bucket" || aws s3 mb s3://performance-reports-bucket --region us-east-1
+          echo "Subiendo resultados de Locust al bucket de S3..."
           aws s3 cp locust_result.html s3://performance-reports-bucket/locust_result.html
-
+          echo "Resultados subidos exitosamente a S3."
