host.docker try ci.yml
Se hace una prueba con el host.docker.internal en vez de localhost

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,12 +51,17 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+
+      - name: Verify LocalStack URL
+        run: |
+          curl -s $LOCALSTACK_URL || echo "Cannot reach LocalStack at $LOCALSTACK_URL"
+
       - name: Deploy to AWS + LocalStack
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
           AWS_DEFAULT_REGION: us-east-1
-          LOCALSTACK_URL: http://localhost:4566
+          LOCALSTACK_URL: http://host.docker.internal:4566
         run: |
           python src/deployment.py
