Update execution23dic.yml

diff --git a/.github/workflows/execution23dic.yml b/.github/workflows/execution23dic.yml
--- a/.github/workflows/execution23dic.yml
+++ b/.github/workflows/execution23dic.yml
@@ -35,14 +35,22 @@ jobs:
       - name: Wait for LocalStack to be ready
         run: |
           for i in {1..90}; do
-            STATUS=$(curl -s http://localhost:4566/health | jq -r '.services.lambda')
-            if [ "$STATUS" = "running" ]; then
+            RESPONSE=$(curl -s http://localhost:4566/health || echo "error")
+            echo "Response: $RESPONSE"
+            if [[ "$RESPONSE" == "error" ]]; then
+              echo "LocalStack is not responding yet..."
+              sleep 5
+              continue
+            fi
+            STATUS=$(echo $RESPONSE | jq -r '.services.lambda // empty')
+            if [[ "$STATUS" == "running" ]]; then
               echo "LocalStack is ready."
               break
             fi
             echo "Waiting for LocalStack to be ready..."
             sleep 5
           done
+
 
       # 6. Verificar el estado de LocalStack
       - name: Verify LocalStack Health
